name: Run Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        if [ ! -f /usr/bin/chromedriver ]; then
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
        fi
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Set environment variables
      run: |
        echo "CHROME_BIN=$(which chromium-browser)" >> $GITHUB_ENV
        echo "CHROMEDRIVER=$(which chromedriver)" >> $GITHUB_ENV

    - name: Run tests
      env:
        PYTHONUNBUFFERED: 1
      run: |
        python -m unittest discover -s tests -v
